version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
